import {GLOBAL_STYLES} from './GLOBAL_STYLES';
import {HOME_STYLES} from './HOME_STYLES';
import {SETTINGS} from './SETTINGS';
import {CONTROL} from './CONTROL_STYLES';
import {STEP_STYLES} from './STEP_STYLES';
import {GRAPH} from './GRAPH_STYLES';

export {CONTROL, GLOBAL_STYLES, HOME_STYLES, SETTINGS, STEP_STYLES, GRAPH};
