import {AUTH_STYLES} from './AUTH_STYLES';
import {GLOBAL_STYLES} from './GLOBAL_STYLES';
import {HOME_STYLES} from './HOME_STYLES';
import {SETTING_STYLES} from './SETTING_STYLES';
import {STEP_STYLES} from './STEP_STYLES';

export {AUTH_STYLES, GLOBAL_STYLES, HOME_STYLES, SETTING_STYLES, STEP_STYLES};
