import {COLORS, SIZES} from '../constants';

export const STEP_STYLES = {
  stepIndicatorSize: SIZES.padding * 2,
  currentStepIndicatorSize: 35,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: COLORS.accent,
  stepStrokeWidth: 2,
  stepStrokeFinishedColor: COLORS.accent,
  stepStrokeUnFinishedColor: COLORS.darkGray,
  separatorFinishedColor: COLORS.accent,
  separatorUnFinishedColor: COLORS.darkGray,
  stepIndicatorFinishedColor: COLORS.accent,
  stepIndicatorUnFinishedColor: COLORS.background,
  stepIndicatorCurrentColor: COLORS.background,
  stepIndicatorLabelFontSize: SIZES.body4,
  currentStepIndicatorLabelFontSize: SIZES.body2,
  stepIndicatorLabelCurrentColor: COLORS.accent,
  stepIndicatorLabelFinishedColor: COLORS.white,
  stepIndicatorLabelUnFinishedColor: COLORS.darkGray,
  labelColor: COLORS.darkGray,
  labelSize: SIZES.body4,
  currentStepLabelColor: COLORS.accent,
};
