import {COLORS, SIZES} from '../constants';

export const STEP_STYLES = {
  stepIndicatorSize: SIZES.padding * 2,
  currentStepIndicatorSize: 35,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: COLORS.secondary,
  stepStrokeWidth: 2,
  stepStrokeFinishedColor: COLORS.secondary,
  stepStrokeUnFinishedColor: COLORS.darkGray,
  separatorFinishedColor: COLORS.secondary,
  separatorUnFinishedColor: COLORS.darkGray,
  stepIndicatorFinishedColor: COLORS.secondary,
  stepIndicatorUnFinishedColor: COLORS.background,
  stepIndicatorCurrentColor: COLORS.background,
  stepIndicatorLabelFontSize: SIZES.body4,
  currentStepIndicatorLabelFontSize: SIZES.body2,
  stepIndicatorLabelCurrentColor: COLORS.secondary,
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnFinishedColor: COLORS.darkGray,
  labelColor: COLORS.darkGray,
  labelSize: SIZES.body4,
  currentStepLabelColor: COLORS.secondary,
};
